---
dependencies:
  cupertino_icons: ^1.0.4
  cloud_firestore: ^3.1.5
  import_sorter: any
  logger: any
  get: ^4.6.1
  firebase_auth: ^3.3.4
  firebase_core: ^1.10.6
  animated_text_kit: ^4.2.1
  font_awesome_flutter: ^9.0.0
  ndialog: ^4.1.0
  fluttertoast: ^8.0.8
  flutter:
    sdk: flutter
description: Smart Retail Solution
dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
environment:
  sdk: '>=2.15.0 <3.0.0'
flutter:
  assets:
    - assets/logo.png
    - assets/alucard.jpg
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/Nunito.ttf
  uses-material-design: true
name: smart_retail
publish_to: none
version: 1.0.0+1